//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturacionElectronica.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FacturacionElectronica.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;2.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:fn=&quot;http://www.w3.org/2005/xpath-functions&quot; xmlns:cfdi=&quot;http://www.sat.gob.mx/cfd/3&quot; xmlns:ecc=&quot;http://www.sat.gob.mx/ecc&quot; xmlns:psgecfd=&quot;http://www.sat.gob.mx/psgecfd&quot; xmlns:donat=&quot;http://www.sat.gob.mx/donat&quot; xmlns:divisas=&quot;http://www.sat.gob.mx/divisas&quot; xmlns:detallista=&quot;http://www.sat.gob.mx/detallista&quot; xmlns:ecb=&quot;http://www.sat.gob.mx/e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cadenaoriginal_3_2 {
            get {
                return ResourceManager.GetString("cadenaoriginal_3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///
        ///	&lt;xsl:output method=&quot;xml&quot; version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; indent=&quot;yes&quot;/&gt;
        ///
        ///	&lt;xsl:template match=&quot;/FacturaElectronica&quot;&gt;
        ///		&lt;Comprobante
        ///			xmlns=&quot;http://www.sat.gob.mx/cfd/3&quot;
        ///			xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///			xsi:schemaLocation=&quot;http://www.sat.gob.mx/cfd/3 http://www.sat.gob.mx/cfd/3/cfdv32.xsd&quot;
        ///		&gt;
        ///
        ///			&lt;!-- Variables de totales --&gt;
        ///			&lt;xsl:variable nam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Cfdi3_2 {
            get {
                return ResourceManager.GetString("Cfdi3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- edited with XMLSpy v2010 rel. 3 (http://www.altova.com) by SAT (SAT) --&gt;
        ///&lt;xs:schema xmlns:cfdi=&quot;http://www.sat.gob.mx/cfd/3&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; targetNamespace=&quot;http://www.sat.gob.mx/cfd/3&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;&gt;
        ///	&lt;xs:element name=&quot;Comprobante&quot;&gt;
        ///		&lt;xs:annotation&gt;
        ///			&lt;xs:documentation&gt;Estándar de Comprobante fiscal digital a través de Internet.&lt;/xs:documentation&gt;
        ///		&lt;/xs:annotation&gt;
        ///		&lt;xs:co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cfdv32 {
            get {
                return ResourceManager.GetString("cfdv32", resourceCulture);
            }
        }
    }
}
