//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ControlRefaccionariaModel", "FK_Sucursal_Usuario", "Usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Theos.Proyectos.TheosProc.Usuario), "Sucursal", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Theos.Proyectos.TheosProc.Sucursal), true)]

#endregion

namespace Theos.Proyectos.TheosProc
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ControlRefaccionariaEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ControlRefaccionariaEntities object using the connection string found in the 'ControlRefaccionariaEntities' section of the application configuration file.
        /// </summary>
        public ControlRefaccionariaEntities() : base("name=ControlRefaccionariaEntities", "ControlRefaccionariaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ControlRefaccionariaEntities object.
        /// </summary>
        public ControlRefaccionariaEntities(string connectionString) : base(connectionString, "ControlRefaccionariaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ControlRefaccionariaEntities object.
        /// </summary>
        public ControlRefaccionariaEntities(EntityConnection connection) : base(connection, "ControlRefaccionariaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MovimientoInventarioTraspasosView> MovimientoInventarioTraspasosView
        {
            get
            {
                if ((_MovimientoInventarioTraspasosView == null))
                {
                    _MovimientoInventarioTraspasosView = base.CreateObjectSet<MovimientoInventarioTraspasosView>("MovimientoInventarioTraspasosView");
                }
                return _MovimientoInventarioTraspasosView;
            }
        }
        private ObjectSet<MovimientoInventarioTraspasosView> _MovimientoInventarioTraspasosView;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Sucursal> Sucursal
        {
            get
            {
                if ((_Sucursal == null))
                {
                    _Sucursal = base.CreateObjectSet<Sucursal>("Sucursal");
                }
                return _Sucursal;
            }
        }
        private ObjectSet<Sucursal> _Sucursal;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Usuario> Usuario
        {
            get
            {
                if ((_Usuario == null))
                {
                    _Usuario = base.CreateObjectSet<Usuario>("Usuario");
                }
                return _Usuario;
            }
        }
        private ObjectSet<Usuario> _Usuario;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MovimientoInventarioTraspasosView EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMovimientoInventarioTraspasosView(MovimientoInventarioTraspasosView movimientoInventarioTraspasosView)
        {
            base.AddObject("MovimientoInventarioTraspasosView", movimientoInventarioTraspasosView);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Sucursal EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSucursal(Sucursal sucursal)
        {
            base.AddObject("Sucursal", sucursal);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Usuario EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsuario(Usuario usuario)
        {
            base.AddObject("Usuario", usuario);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ControlRefaccionariaModel", Name="MovimientoInventarioTraspasosView")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MovimientoInventarioTraspasosView : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MovimientoInventarioTraspasosView object.
        /// </summary>
        /// <param name="movimientoInventarioID">Initial value of the MovimientoInventarioID property.</param>
        /// <param name="tipoOperacionID">Initial value of the TipoOperacionID property.</param>
        /// <param name="origen">Initial value of the Origen property.</param>
        /// <param name="destino">Initial value of the Destino property.</param>
        /// <param name="registro">Initial value of the Registro property.</param>
        public static MovimientoInventarioTraspasosView CreateMovimientoInventarioTraspasosView(global::System.Int32 movimientoInventarioID, global::System.Int32 tipoOperacionID, global::System.String origen, global::System.String destino, global::System.String registro)
        {
            MovimientoInventarioTraspasosView movimientoInventarioTraspasosView = new MovimientoInventarioTraspasosView();
            movimientoInventarioTraspasosView.MovimientoInventarioID = movimientoInventarioID;
            movimientoInventarioTraspasosView.TipoOperacionID = tipoOperacionID;
            movimientoInventarioTraspasosView.Origen = origen;
            movimientoInventarioTraspasosView.Destino = destino;
            movimientoInventarioTraspasosView.Registro = registro;
            return movimientoInventarioTraspasosView;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MovimientoInventarioID
        {
            get
            {
                return _MovimientoInventarioID;
            }
            set
            {
                if (_MovimientoInventarioID != value)
                {
                    OnMovimientoInventarioIDChanging(value);
                    ReportPropertyChanging("MovimientoInventarioID");
                    _MovimientoInventarioID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MovimientoInventarioID");
                    OnMovimientoInventarioIDChanged();
                }
            }
        }
        private global::System.Int32 _MovimientoInventarioID;
        partial void OnMovimientoInventarioIDChanging(global::System.Int32 value);
        partial void OnMovimientoInventarioIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TipoOperacionID
        {
            get
            {
                return _TipoOperacionID;
            }
            set
            {
                if (_TipoOperacionID != value)
                {
                    OnTipoOperacionIDChanging(value);
                    ReportPropertyChanging("TipoOperacionID");
                    _TipoOperacionID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TipoOperacionID");
                    OnTipoOperacionIDChanged();
                }
            }
        }
        private global::System.Int32 _TipoOperacionID;
        partial void OnTipoOperacionIDChanging(global::System.Int32 value);
        partial void OnTipoOperacionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SucursalOrigenID
        {
            get
            {
                return _SucursalOrigenID;
            }
            set
            {
                OnSucursalOrigenIDChanging(value);
                ReportPropertyChanging("SucursalOrigenID");
                _SucursalOrigenID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SucursalOrigenID");
                OnSucursalOrigenIDChanged();
            }
        }
        private Nullable<global::System.Int32> _SucursalOrigenID;
        partial void OnSucursalOrigenIDChanging(Nullable<global::System.Int32> value);
        partial void OnSucursalOrigenIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Origen
        {
            get
            {
                return _Origen;
            }
            set
            {
                if (_Origen != value)
                {
                    OnOrigenChanging(value);
                    ReportPropertyChanging("Origen");
                    _Origen = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Origen");
                    OnOrigenChanged();
                }
            }
        }
        private global::System.String _Origen;
        partial void OnOrigenChanging(global::System.String value);
        partial void OnOrigenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SucursalDestinoID
        {
            get
            {
                return _SucursalDestinoID;
            }
            set
            {
                OnSucursalDestinoIDChanging(value);
                ReportPropertyChanging("SucursalDestinoID");
                _SucursalDestinoID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SucursalDestinoID");
                OnSucursalDestinoIDChanged();
            }
        }
        private Nullable<global::System.Int32> _SucursalDestinoID;
        partial void OnSucursalDestinoIDChanging(Nullable<global::System.Int32> value);
        partial void OnSucursalDestinoIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Destino
        {
            get
            {
                return _Destino;
            }
            set
            {
                if (_Destino != value)
                {
                    OnDestinoChanging(value);
                    ReportPropertyChanging("Destino");
                    _Destino = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Destino");
                    OnDestinoChanged();
                }
            }
        }
        private global::System.String _Destino;
        partial void OnDestinoChanging(global::System.String value);
        partial void OnDestinoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaRegistro
        {
            get
            {
                return _FechaRegistro;
            }
            set
            {
                OnFechaRegistroChanging(value);
                ReportPropertyChanging("FechaRegistro");
                _FechaRegistro = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaRegistro");
                OnFechaRegistroChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaRegistro;
        partial void OnFechaRegistroChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaRegistroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Registro
        {
            get
            {
                return _Registro;
            }
            set
            {
                if (_Registro != value)
                {
                    OnRegistroChanging(value);
                    ReportPropertyChanging("Registro");
                    _Registro = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Registro");
                    OnRegistroChanged();
                }
            }
        }
        private global::System.String _Registro;
        partial void OnRegistroChanging(global::System.String value);
        partial void OnRegistroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Solicito
        {
            get
            {
                return _Solicito;
            }
            set
            {
                OnSolicitoChanging(value);
                ReportPropertyChanging("Solicito");
                _Solicito = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Solicito");
                OnSolicitoChanged();
            }
        }
        private global::System.String _Solicito;
        partial void OnSolicitoChanging(global::System.String value);
        partial void OnSolicitoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaRecepcion
        {
            get
            {
                return _FechaRecepcion;
            }
            set
            {
                OnFechaRecepcionChanging(value);
                ReportPropertyChanging("FechaRecepcion");
                _FechaRecepcion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaRecepcion");
                OnFechaRecepcionChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaRecepcion;
        partial void OnFechaRecepcionChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaRecepcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Recibio
        {
            get
            {
                return _Recibio;
            }
            set
            {
                OnRecibioChanging(value);
                ReportPropertyChanging("Recibio");
                _Recibio = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Recibio");
                OnRecibioChanged();
            }
        }
        private global::System.String _Recibio;
        partial void OnRecibioChanging(global::System.String value);
        partial void OnRecibioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Observacion
        {
            get
            {
                return _Observacion;
            }
            set
            {
                OnObservacionChanging(value);
                ReportPropertyChanging("Observacion");
                _Observacion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Observacion");
                OnObservacionChanged();
            }
        }
        private global::System.String _Observacion;
        partial void OnObservacionChanging(global::System.String value);
        partial void OnObservacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> TraspasoEntregado
        {
            get
            {
                return _TraspasoEntregado;
            }
            set
            {
                OnTraspasoEntregadoChanging(value);
                ReportPropertyChanging("TraspasoEntregado");
                _TraspasoEntregado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TraspasoEntregado");
                OnTraspasoEntregadoChanged();
            }
        }
        private Nullable<global::System.Boolean> _TraspasoEntregado;
        partial void OnTraspasoEntregadoChanging(Nullable<global::System.Boolean> value);
        partial void OnTraspasoEntregadoChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ControlRefaccionariaModel", Name="Sucursal")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Sucursal : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Sucursal object.
        /// </summary>
        /// <param name="sucursalID">Initial value of the SucursalID property.</param>
        /// <param name="nombreSucursal">Initial value of the NombreSucursal property.</param>
        /// <param name="usuarioID">Initial value of the UsuarioID property.</param>
        /// <param name="fechaRegistro">Initial value of the FechaRegistro property.</param>
        /// <param name="estatus">Initial value of the Estatus property.</param>
        /// <param name="actualizar">Initial value of the Actualizar property.</param>
        public static Sucursal CreateSucursal(global::System.Int32 sucursalID, global::System.String nombreSucursal, global::System.Int32 usuarioID, global::System.DateTime fechaRegistro, global::System.Boolean estatus, global::System.Boolean actualizar)
        {
            Sucursal sucursal = new Sucursal();
            sucursal.SucursalID = sucursalID;
            sucursal.NombreSucursal = nombreSucursal;
            sucursal.UsuarioID = usuarioID;
            sucursal.FechaRegistro = fechaRegistro;
            sucursal.Estatus = estatus;
            sucursal.Actualizar = actualizar;
            return sucursal;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SucursalID
        {
            get
            {
                return _SucursalID;
            }
            set
            {
                if (_SucursalID != value)
                {
                    OnSucursalIDChanging(value);
                    ReportPropertyChanging("SucursalID");
                    _SucursalID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SucursalID");
                    OnSucursalIDChanged();
                }
            }
        }
        private global::System.Int32 _SucursalID;
        partial void OnSucursalIDChanging(global::System.Int32 value);
        partial void OnSucursalIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NombreSucursal
        {
            get
            {
                return _NombreSucursal;
            }
            set
            {
                OnNombreSucursalChanging(value);
                ReportPropertyChanging("NombreSucursal");
                _NombreSucursal = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NombreSucursal");
                OnNombreSucursalChanged();
            }
        }
        private global::System.String _NombreSucursal;
        partial void OnNombreSucursalChanging(global::System.String value);
        partial void OnNombreSucursalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DireccionIP
        {
            get
            {
                return _DireccionIP;
            }
            set
            {
                OnDireccionIPChanging(value);
                ReportPropertyChanging("DireccionIP");
                _DireccionIP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DireccionIP");
                OnDireccionIPChanged();
            }
        }
        private global::System.String _DireccionIP;
        partial void OnDireccionIPChanging(global::System.String value);
        partial void OnDireccionIPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UsuarioID
        {
            get
            {
                return _UsuarioID;
            }
            set
            {
                OnUsuarioIDChanging(value);
                ReportPropertyChanging("UsuarioID");
                _UsuarioID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UsuarioID");
                OnUsuarioIDChanged();
            }
        }
        private global::System.Int32 _UsuarioID;
        partial void OnUsuarioIDChanging(global::System.Int32 value);
        partial void OnUsuarioIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaRegistro
        {
            get
            {
                return _FechaRegistro;
            }
            set
            {
                OnFechaRegistroChanging(value);
                ReportPropertyChanging("FechaRegistro");
                _FechaRegistro = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaRegistro");
                OnFechaRegistroChanged();
            }
        }
        private global::System.DateTime _FechaRegistro;
        partial void OnFechaRegistroChanging(global::System.DateTime value);
        partial void OnFechaRegistroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaModificacion
        {
            get
            {
                return _FechaModificacion;
            }
            set
            {
                OnFechaModificacionChanging(value);
                ReportPropertyChanging("FechaModificacion");
                _FechaModificacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaModificacion");
                OnFechaModificacionChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaModificacion;
        partial void OnFechaModificacionChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaModificacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Estatus
        {
            get
            {
                return _Estatus;
            }
            set
            {
                OnEstatusChanging(value);
                ReportPropertyChanging("Estatus");
                _Estatus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Estatus");
                OnEstatusChanged();
            }
        }
        private global::System.Boolean _Estatus;
        partial void OnEstatusChanging(global::System.Boolean value);
        partial void OnEstatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Actualizar
        {
            get
            {
                return _Actualizar;
            }
            set
            {
                OnActualizarChanging(value);
                ReportPropertyChanging("Actualizar");
                _Actualizar = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Actualizar");
                OnActualizarChanged();
            }
        }
        private global::System.Boolean _Actualizar;
        partial void OnActualizarChanging(global::System.Boolean value);
        partial void OnActualizarChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ControlRefaccionariaModel", "FK_Sucursal_Usuario", "Usuario")]
        public Usuario Usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("ControlRefaccionariaModel.FK_Sucursal_Usuario", "Usuario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("ControlRefaccionariaModel.FK_Sucursal_Usuario", "Usuario").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Usuario> UsuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("ControlRefaccionariaModel.FK_Sucursal_Usuario", "Usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Usuario>("ControlRefaccionariaModel.FK_Sucursal_Usuario", "Usuario", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ControlRefaccionariaModel", Name="Usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Usuario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Usuario object.
        /// </summary>
        /// <param name="usuarioID">Initial value of the UsuarioID property.</param>
        /// <param name="nombrePersona">Initial value of the NombrePersona property.</param>
        /// <param name="nombreUsuario">Initial value of the NombreUsuario property.</param>
        /// <param name="contrasenia">Initial value of the Contrasenia property.</param>
        /// <param name="fechaRegistro">Initial value of the FechaRegistro property.</param>
        /// <param name="estatus">Initial value of the Estatus property.</param>
        /// <param name="actualizar">Initial value of the Actualizar property.</param>
        /// <param name="activo">Initial value of the Activo property.</param>
        public static Usuario CreateUsuario(global::System.Int32 usuarioID, global::System.String nombrePersona, global::System.String nombreUsuario, global::System.String contrasenia, global::System.DateTime fechaRegistro, global::System.Boolean estatus, global::System.Boolean actualizar, global::System.Boolean activo)
        {
            Usuario usuario = new Usuario();
            usuario.UsuarioID = usuarioID;
            usuario.NombrePersona = nombrePersona;
            usuario.NombreUsuario = nombreUsuario;
            usuario.Contrasenia = contrasenia;
            usuario.FechaRegistro = fechaRegistro;
            usuario.Estatus = estatus;
            usuario.Actualizar = actualizar;
            usuario.Activo = activo;
            return usuario;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UsuarioID
        {
            get
            {
                return _UsuarioID;
            }
            set
            {
                if (_UsuarioID != value)
                {
                    OnUsuarioIDChanging(value);
                    ReportPropertyChanging("UsuarioID");
                    _UsuarioID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UsuarioID");
                    OnUsuarioIDChanged();
                }
            }
        }
        private global::System.Int32 _UsuarioID;
        partial void OnUsuarioIDChanging(global::System.Int32 value);
        partial void OnUsuarioIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NombrePersona
        {
            get
            {
                return _NombrePersona;
            }
            set
            {
                OnNombrePersonaChanging(value);
                ReportPropertyChanging("NombrePersona");
                _NombrePersona = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NombrePersona");
                OnNombrePersonaChanged();
            }
        }
        private global::System.String _NombrePersona;
        partial void OnNombrePersonaChanging(global::System.String value);
        partial void OnNombrePersonaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NombreUsuario
        {
            get
            {
                return _NombreUsuario;
            }
            set
            {
                OnNombreUsuarioChanging(value);
                ReportPropertyChanging("NombreUsuario");
                _NombreUsuario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NombreUsuario");
                OnNombreUsuarioChanged();
            }
        }
        private global::System.String _NombreUsuario;
        partial void OnNombreUsuarioChanging(global::System.String value);
        partial void OnNombreUsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Contrasenia
        {
            get
            {
                return _Contrasenia;
            }
            set
            {
                OnContraseniaChanging(value);
                ReportPropertyChanging("Contrasenia");
                _Contrasenia = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Contrasenia");
                OnContraseniaChanged();
            }
        }
        private global::System.String _Contrasenia;
        partial void OnContraseniaChanging(global::System.String value);
        partial void OnContraseniaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaRegistro
        {
            get
            {
                return _FechaRegistro;
            }
            set
            {
                OnFechaRegistroChanging(value);
                ReportPropertyChanging("FechaRegistro");
                _FechaRegistro = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaRegistro");
                OnFechaRegistroChanged();
            }
        }
        private global::System.DateTime _FechaRegistro;
        partial void OnFechaRegistroChanging(global::System.DateTime value);
        partial void OnFechaRegistroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaModificacion
        {
            get
            {
                return _FechaModificacion;
            }
            set
            {
                OnFechaModificacionChanging(value);
                ReportPropertyChanging("FechaModificacion");
                _FechaModificacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaModificacion");
                OnFechaModificacionChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaModificacion;
        partial void OnFechaModificacionChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaModificacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Estatus
        {
            get
            {
                return _Estatus;
            }
            set
            {
                OnEstatusChanging(value);
                ReportPropertyChanging("Estatus");
                _Estatus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Estatus");
                OnEstatusChanged();
            }
        }
        private global::System.Boolean _Estatus;
        partial void OnEstatusChanging(global::System.Boolean value);
        partial void OnEstatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Actualizar
        {
            get
            {
                return _Actualizar;
            }
            set
            {
                OnActualizarChanging(value);
                ReportPropertyChanging("Actualizar");
                _Actualizar = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Actualizar");
                OnActualizarChanged();
            }
        }
        private global::System.Boolean _Actualizar;
        partial void OnActualizarChanging(global::System.Boolean value);
        partial void OnActualizarChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> AlertaPedidos
        {
            get
            {
                return _AlertaPedidos;
            }
            set
            {
                OnAlertaPedidosChanging(value);
                ReportPropertyChanging("AlertaPedidos");
                _AlertaPedidos = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AlertaPedidos");
                OnAlertaPedidosChanged();
            }
        }
        private Nullable<global::System.Boolean> _AlertaPedidos;
        partial void OnAlertaPedidosChanging(Nullable<global::System.Boolean> value);
        partial void OnAlertaPedidosChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> AlertaCalendarioClientes
        {
            get
            {
                return _AlertaCalendarioClientes;
            }
            set
            {
                OnAlertaCalendarioClientesChanging(value);
                ReportPropertyChanging("AlertaCalendarioClientes");
                _AlertaCalendarioClientes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AlertaCalendarioClientes");
                OnAlertaCalendarioClientesChanged();
            }
        }
        private Nullable<global::System.Boolean> _AlertaCalendarioClientes;
        partial void OnAlertaCalendarioClientesChanging(Nullable<global::System.Boolean> value);
        partial void OnAlertaCalendarioClientesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Activo
        {
            get
            {
                return _Activo;
            }
            set
            {
                OnActivoChanging(value);
                ReportPropertyChanging("Activo");
                _Activo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Activo");
                OnActivoChanged();
            }
        }
        private global::System.Boolean _Activo;
        partial void OnActivoChanging(global::System.Boolean value);
        partial void OnActivoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TipoUsuarioID
        {
            get
            {
                return _TipoUsuarioID;
            }
            set
            {
                OnTipoUsuarioIDChanging(value);
                ReportPropertyChanging("TipoUsuarioID");
                _TipoUsuarioID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TipoUsuarioID");
                OnTipoUsuarioIDChanged();
            }
        }
        private Nullable<global::System.Int32> _TipoUsuarioID;
        partial void OnTipoUsuarioIDChanging(Nullable<global::System.Int32> value);
        partial void OnTipoUsuarioIDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ControlRefaccionariaModel", "FK_Sucursal_Usuario", "Sucursal")]
        public EntityCollection<Sucursal> Sucursal
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Sucursal>("ControlRefaccionariaModel.FK_Sucursal_Usuario", "Sucursal");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Sucursal>("ControlRefaccionariaModel.FK_Sucursal_Usuario", "Sucursal", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
